services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./frontend/www:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go-api

  go-api:
    build: ./go-backend
    container_name: go_api
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env